Repository kubernetes/committee-security-response, pull requests merged in 2020-07, with the labels that each got.

#98 Onboard Swamy to PSC
  OWNERS_ALIASES
  README.md
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/XS

#100 Onboarding: clarify that role on k-announce is manager, not owner
  psc-onboarding-offboarding.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/XS

#96 Add an email template for distributors-announce notifications
  comms-templates/distributors-announcement-email.md
  comms-templates/vulnerability-announcement-email.md
  comms-templates/vulnerability-announcement-issue.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/M

#102 Fix broken link to contributor cheatsheet
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/XS

#103 Fix "informing" spelling error and link to adjacent-network-access
  security-release-process.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/XS

#106 PSC On-call should review new k/security PRs and issues
  psc-oncall.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/XS

#107 Add repo SECURITY.md
  SECURITY.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/S

#104 Add Alex Tcherniakhovski as an associate member
  README.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/XS
