Repository kubernetes/committee-security-response, pull requests merged in 2020-03, with the labels that each got.

#69 Update CNA handbook
  cna-handbook.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/S

#70 PSC on/offboarding
  OWNERS_ALIASES
  README.md
  psc-onboarding-offboarding.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/M

#71 Fix typos
  psc-onboarding-offboarding.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/S

#72 Add Craig Ingram (@cji) as associate member
  README.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/XS

#74 Update oncall responsibilities with links to queries
  psc-oncall.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/S

#73 Proposal to add Mo Khan as an associate member
  README.md
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/XS

#76 Remove @jonpulsifer, @philips from SECURITY_CONTACTS, add @micahhausler
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, committee/product-security, lgtm, size/XS
